import type { Metadata } from 'next'
import '@picocss/pico'
import Navbar from './components/Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main>
        <Navbar />
          {children}
        </main>
      </body>
    </html>
  )
}
